train_data_path : /home/mtftau-5/workplace/shl-code/data/fft_data/train/data.npy
train_label_path : /home/mtftau-5/workplace/shl-code/data/fft_data/train/label.npy
test_data_path : /home/mtftau-5/workplace/shl-code/data/fft_data/test/data.npy
valid_label_path : /home/mtftau-5/workplace/shl-code/data/fft_data/valid/label.npy
valid_data_path: /home/mtftau-5/workplace/shl-code/data/fft_data/valid/data.npy
batch_size : 16
epochs : 10
cnn_channels : 9
num_classes : 9
num_clusters : num_classes 
update_interval : 5 
num_epochs : 10
lr : 0.0001
input_size: 1071